CodecademyCommunity/codecademy-discord-bot

- CONTRIBUTING.md
Now that we have a wiki, I thought it would be better to move some of the more basic information off CONTRIBUTING.md
I left the section with a little blurb telling people to go to the wiki if they need help. closes #23
> Deleted Git workflow, moved to wiki

- app.js
- commands/utility/help.js
> Change trigger from ! to cc!

- app.js
- commands/utility/stats.js
Added 'stats' to the command handler switch in alphabetical order
Added ./commands/utility/stats.js
closes #35
> Added new stats module and switch on app.js

- README.md
Added new commands to list (ban, unban, tempban, kick, mute, unmute, tempmute, stats, ping) and updated bot triggers to _cc!_ from _!_.
> Update README.md to include information about new commands

- app.js
- commands/utility/help.js
Now includes info for ping and stats commands. Now you can also get information about individual commands by typing their name after any of the help commands.
> Updated cc!help command

- app.js
- commands/utility/warn.js
- package-lock.json
This deals with the first half of requirements in #41
The warn command should do:
- DM the offending user
- Log offense to infractions table
> Warn command

- CONTRIBUTING.md
This is just a documentation PR. Closes #22.
All I did was add in a link to the updated DB wiki page, but Prettier auto-formatted the markdown file, so that's why it looks like more changes.
> Add Windows and Linux DB setup instructions

- app.js
- commands/utility/infractions.js
This PR completes command 2 out of 4 in issue #41 . Two down, two to go!
Things this command should do:
- Check the caller has the right roles to use the command
- Check a target user was provided to look up associated infractions
- Query the database for the target user's infractions
- Print back to the caller an embedded message in the channel the command was used
- If target user doesn't have associated infractions, the embedded message will point it out
> cc!infractions

- README.md
Closes #86 
I clean up the Readme file and added collapsible elements to separate admin and other commands and I made a table to add a prettier way of looking for commands.
- Is a re-seeding of the database necessary?
- Any new dependencies to install?
> Readme Collapsible and Tables Created

- package.json
- utils/data/addColumn.js
- utils/data/addTable.js
- utils/data/db.js
- utils/data/dropTable.js
- utils/data/prompt.js
- utils/data/recreate.js
- utils/data/tables.js
Closes #100 
Refactors old database script and adds scripts to create tables, drop tables and add a column
**Adding tables**
You can now add one or more tables if the are defined in `utils/data/tables.js` using the following command:
```bash
npm run addtable table_1 table_2
```
**Deleting tables**
You can now delete one or more tables if the are defined in `utils/data/tables.js` using the following command:
```bash
npm run droptable table_1 table_2
```
**Adding a column**
You can now add one column at a time to any table defined in `utils/data/tables.js` using the following command:
```bash
npm run addcolumn table="table_name" col="column_name" type="COLUMN_TYPE"
```
**Defining a new table in the codebase**
New tables should now be defined in `utils/data/tables.js` in the following …
> Db maintenance scripts

- .gitignore
- README.md
- commands/utility/help.js
Closes #96.
- Add `cc!addnote` to `cc!help` and `README.md`.
- Add `.DS_Store` to gitignore.
- Did not add `package-lock.json` to gitignore; let's try out @aedwardg's [suggestion](https://github.com/CodecademyCommunity/codecademy-discord-bot/issues/96#issuecomment-790996538).
> Add .DS_Store to gitignore, add cc!addnote to README and cc!help

- README.md
- commands/utility/help.js
Closes #115.
Add cc!clearmessages, cc!clearinfractions, cc!removeinfraction, and cc!notes to cc!help and README.md. Also added a note about how [user] parameters can take both user mentions and user IDs.
> Update help and readme

- app.js
- commands/moderation/notes.js
Closes #41 and continues push for issue #7 
Fourth and final command from the infractions and notes family of commands. This is a refactoring of the very functionally-similar `cc!infractions @user` command. It should work out the box.
- Any special requirements to test? Admin/Mod/SU
> Adding `cc!notes @user` command

- commands/utility/helpcenter.js
Closes #120
cc!helpcenter now includes a field that explains how learners can report a bug through the CC learning environment.
> Add bug reporting info to cc!helpcenter

- commands/moderation/filter.js
Repaired regex so it won't catch words like "hello" or "objects/exercise"
Closes #139 
Updated the regex so that it ensures were the start and end of the word is.
- Is a re-seeding of the database necessary?  No
- Any new dependencies to install?  No
- Any special requirements to test?  Must be lower than SU
> Repaired regex

- .github/workflows/format_and_lint.yml
- commands/moderation/addnote.js
- commands/moderation/filter.js
- commands/mute/mute.js
- GitHub Actions workflow added to run the formatting and linting on push/pull to `dev`
- Hot fix for profanity filter to decrease the number of false positives
> Hot-fix profanity filter and add actions workflow

- commands/moderation/notes.js
- commands/utility/infractions.js
Closes #150
Changed underscores to asterisks for italics to allow for links containing underscores to work. Also checked all files: all italics use asterisks.
Ignore earlier attempt #151, I don't really know what happened.
- Any special requirements to test? NO
> Change underscores to asterisks

- commands/moderation/ban.js
- commands/moderation/kick.js
- commands/moderation/tempban.js
Closes #145 
Uses async/await to ensure actions are taken in the proper order for the ban, kick and tempban commands.
- Any special requirements to test? NO
> Add async-await to ban, kick & tempban

- commands/moderation/notes.js
- commands/utility/infractions.js
- commands/utility/warn.js
Closes #174 
Replace 'targer' with 'target' in the codebase.
N/A
N/A
> Fix typos in codebase

- handlers/permissionHandlers.js
No issue for this one.
Change Helper role to Code Counselor.
This change also changes 'Super User' to 'Forums Super User' and lowers
its rank to below Code Counselors. This will effectively strip all
perms from non-promoted super users once the refactoring is done, but
leaves open the possibility for us to have some commands that FSUs can
use that the Member role cannot.
- Is a re-seeding of the database necessary? n/a
- Any new dependencies to install? n/a
- Any special requirements to test? n/a
> Change Helper role to Code Counselor

- README.md
Closes #190 
Update `README.md` with the new permissions required for commands (elimination of the Super User role, addition of the Code Counselor role).
> Update README to reflect new command permissions

- commands/utility/help.js
Closes #193 
Change information given out by `cc!help` to reflect some old changes (Moderators allowed to ban, allowed to unban, etc.) and new changes (elimination of SU role, addition of CoCo role).
- Is a re-seeding of the database necessary? **No**
- Any new dependencies to install? **No**
- Any special requirements to test? **No**
> Update cc!help with new permissions

- .github/workflows/action_workflow.yml
I'm going to just go ahead and merge, this might be a problem to confront later though. Whenever the bot completely crashes, we'll have to fix this, its a thing with pm2.
> Correcting job number

- config/client.js
Closes #219 
Add intents to our bot so it doesn't crash on start up.
- Any new dependencies to install? Make sure you've used `npm install` so that you're running discord.js v13.
> Add intents

- .github/workflows/action_workflow.yml
Deploy Shaylin's word filter to the live bot
> Deploy word filter changes

- commands/utility/help.js
- commands/utility/ping.js
No official issue, but it's been discussed in discord.
Server members are abusing the cc!ping command. At best it is an annoyance, at worst it could cause performance issues for the bot.
- Is a re-seeding of the database necessary?
- ✅ Code has been tested and does not produce errors
- ✅ Code is readable and formatted
- ✅ There isn't any unnecessary commented-out code
> Change cc!ping command to be staff only

- config/client.js
- handlers/messageHandlers.js
Closes #237
Remove partials and go back to default discord.js settings for them since they do not appear to be used in the code. They introduce a risk of data with missing properties and associated errors.
Appreciate some additional testing with removed partials to confirm that it does not add any new issue or cause loss of functionality.
> remove partials and reference to them

- commands/moderation/ban.js
- commands/moderation/unban.js
Closes #244 
Ported cc!ban and cc!unban to v13 branch.
> port cc!ban and cc!unban to v13

- commands/mute/mute.js
- commands/mute/unmute.js
Closes #247 
Ports cc!mute and cc!unmute. Did not do cc!tempmute since it will be removed.
> port mute and unmute to discord.js v13

- commands/utility/clearinfractions.js
- commands/utility/infractions.js
- commands/utility/removeinfraction.js
- commands/utility/warn.js
Closes #251
Ports the infraction commands. Also included the warn command since I needed it for testing the infraction commands. Removed function with random error msg replies from several command files and replaced it with an import of the centralized version in helpers/hasTargetUser.js.
> port infraction commands and warn command to v13

- package-lock.json
- package.json
No official issue
Removes unused uuid dependency that was missed in #236
- Is a re-seeding of the database necessary? :x:
- Any new dependencies to install? Not really, but you can do an npm install if you wanna update the dependencies on your system.
- Any special requirements to test? :x:
> remove unused uuid dependency

- commands/moderation/filter.js
- config/db.js
- config/filters.js
- package-lock.json
- package.json
Closes #246 
Ported filter to work in V13 and reformatted.
Removed auto moderation functions since we've gone on the path of not using them. 
Rewrote to use `RoleEnum` instead of `isHighRoller`.
Rewrote conversion function to use an object, and `.map()` instead of the spaghetti mess of `||`s.
- Is a re-seeding of the database necessary? 
no
- Any new dependencies to install? 
Uses bad-words library from https://www.npmjs.com/package/bad-words
- Any special requirements to test? 
Filter ignores any account with code-counselor or higher, so test account cannot have those.
> Port filter v13

- commands/moderation/clearmessages.js
- handlers/messageHandlers.js
Closes #254
Port cc!clearmessages. Added validation for a negative integer (which would throw an API error) and zero for number of messages.
> port cc!clearmessages to discord.js v13

- commands/moderation/kick.js
Closes #259
Updates kick command to work with v13
- Is a re-seeding of the database necessary? :x:
- Any new dependencies to install? :x:
- Any special requirements to test? Double check that it logs to the database.
> update kick command to work with v13

- commands/moderation/verbal.js
Closes #252
Port verbal command to v13.
- Any special requirements to test? Must be Mod or above to use command.
> Port verbal command to v13

- commands/moderation/addnote.js
- commands/moderation/filter.js
- commands/moderation/notes.js
- commands/moderation/removenote.js
- config/filters.js
Closes #232 
Ports the three notes commands over to v13.
> Port notes commands

- commands/utility/removeinfraction.js
Closes #266
Fixes bug where TypeError would occur if using cc!removeinfraction with invalid id.
> fix bug removeinfraction with wrong id

- package-lock.json
- package.json
Closes #239
Added MIT license and updated package.json engines property to use node v16.6 or higher. Updated dependencies to latest non-breaking changes (reflected in package-lock.json).
> update MIT license, package.json and dependencies

- .github/workflows/action_workflow.yml
- .github/workflows/format_and_lint.yml
> Update GH Action workflows

- CONTRIBUTING.md
Closes #312 
* Added that `applications.commands` should be checked under the Scopes section in the Discord developer portal.
* Edited instructions to ask contributors to physically copy the contents of `sample.env` to their own `.env` file instead of running a terminal command. This is because the `cp` command only works on Linux, Mac, and Powershell. If users are using Windows Command Prompt, the command will not work.
* Minor grammatical edits.
> Update Discord application scope and .env instructions

- config/slashCommandPermissions.js
- helpers/stringHelpers.js
- slash-commands/moderation/verbal.js
Closes #300
Converts cc!verbal to a slash command.
- Any special requirements to test? Send a verbal to test account.
> convert verbal command to slash cmd

- config/slashCommandPermissions.js
- slash-commands/moderation/removetimeout.js
- slash-commands/moderation/timeout.js
Closes #315 
* Add slash command for removing timeouts.
* Action gets logged to the #audit-logs channel and recorded in the mod_log table of the db.
- Any special requirements to test? Minimum role required to remove timeout is Moderator.
> Add remove timeout slash command

- config/slashCommandPermissions.js
- slash-commands/moderation/kick.js
Closes #298 
Adds the kick slash command. The command is now able to kick a user who has DMs disabled.
> adds kick slash command

- config/slashCommandPermissions.js
- slash-commands/moderation/infractions.js
Closes #302 
Adds the infractions slash command
Nope
- Any special requirements to test? ✔️ Make sure to run `npm run deploy:commands` before starting the bot
> Infractions slash command

- helpers/sendToAuditLogs.js
- package-lock.json
- package.json
- slash-commands/moderation/addnote.js
- slash-commands/moderation/ban.js
- slash-commands/moderation/notes.js
- slash-commands/moderation/timeout.js
- slash-commands/moderation/verbal.js
- slash-commands/utility/helpcenter.js
No official issue, but recommended in the dev server here:
https://discord.com/channels/810930683732033597/810930684171780117/981746378424328252
Updates Discord.js and related dependencies.
- Is a re-seeding of the database necessary? :x:
- Any new dependencies to install? :heavy_check_mark:
- Any special requirements to test? Make sure everything still works
> Update Discord.js dependencies

- config/slashCommandPermissions.js
- slash-commands/utility/warn.js
Closes #303
Creates the warn slash-command.
Run the deployCommands script before testing the bot.
> add warn slash-cmd

- config/slashCommandPermissions.js
- presenters/dataPresenters.js
- presenters/logPresenters.js
- slash-commands/moderation/infractions.js
- slash-commands/moderation/notes.js
- slash-commands/moderation/records.js
Closes #299 
- Adds records slash command
- Refactors notes and infractions commands to make records cleaner that it otherwise would have been.
⚠️ This branch is based on the branch that implements the infractions command, so it shows an extra commit right now.  I will rebase it once the PR for the infractions command has been merged into `dev`
- Any special requirements to test? ✔️ Make sure to run `npm run deploy:commands` before starting the bot.
> Records slash command

- .github/workflows/action_workflow.yml
No official issue, just getting ready for deploying slash commands
Added the `deploy:commands` script to our deploy action.  This is needed to make slash commands available in the main server when deploying new code.
> Update CI to deploy slash comands

- .github/workflows/action_workflow.yml
- CONTRIBUTING.md
- LICENSE
- package.json
Closes #329 
Changed all names of multi-word scripts to use dashes between each word. Any references or uses of the scripts in other files were updated to reflect the new convention.
Also updated our license copyright statement to the current year.
> Standardize script names

- slash-commands/moderation/clearmessages.js
Closes #338
Adds an error message presented to the user when bulk-deleting messages that are >= 14 days old. This makes it clear to the user why the command failed so it can be attempted with fewer messages.
- Any special requirements to test? 
> add clearmessages user error msg for >= 14 days old msg

- config/slashCommandPermissions.js
- slash-commands/utility/clearinfractions.js
Closes #344 
Adds the clearinfractions slash command for admin and above.
> add clearinfractions slash cmd

- config/slashCommandPermissions.js
- slash-commands/utility/removeinfraction.js
Closes #343
Adds removeinfraction slash command. This command was fairly similar in logic to removenote so it uses similar code.
> add removeinfraction slash cmd
