- commands/utility/stats.js
closes #45 
the stats command was using <guild>.members.cache to count the total number of online and offline members on the server.
Problem is, not everyone is in the cache.
Fixed by async fetching all members and then (similar to pre-fix) parsing through members based on presence status.
> Fixed incorrect online/offline user count

- commands/discourse/sendcode.js
- package-lock.json
- package.json
- utils/data/db.js
Closes #15 
You can wipe the MySQL database and re-create all tables from scratch.
To use this new script, run the following command:
```bash
$ npm run db-recreate 
```
- Adds new script to drop and recreate all current tables in the db.
- This is mostly for dev/testing purposes and getting new contributors
up and running.
- Adds new script command and `dateformat` dependency in `package.json`
- Uses new MySQL datetime format in `sendcode.js`
This script is for MySQL, but we may change over to Mongo in the future.
Whichever database we choose, it may be wise to switch over to an ORM
for database interaction. For MySQL, we could use [Sequelize](https://sequelize.org/master/index.html), for Mongo
we could use [Mongoose](https://mongoosejs.com/).
---
- Any new dependencies to install (`npm …
> Add MySQL db recreate script

- app.js
Add the oldMember parameter to the guildMemberUpdate event listener. Fixes the problem where users weren't being denied message sending and role reacting privileges.
> Fix denying of permissions to users with the Muted role

- app.js
Include the channel name in the log of the deleted message. This doesn't solve a specific issue, but does make the logs more effective, especially for messages removed because they were in the wrong channel.
> Add channel name to log of deleted message

- commands/mute/tempmute.js
- commands/mute/unmute.js
cc!unmute is only recorded in mod_log now, not infractions. The muting part of cc!tempmute is still recorded in both infractions and mod_log, but the unmuting part is now only recorded in mod_log and not infractions.
This is done so that unmutes and the unmuting part of tempmute will not be shown in a user's infractions when the cc!infractions command is used. Closes #67.
> Record unmute and unmuting part of tempmute only in mod_log

- commands/mute/mute.js
- commands/mute/tempmute.js
- commands/mute/unmute.js
Closes #71.
Escape values used in SQL queries and eliminate the need to use `multipleStatements: true` as an attribute of the database connection. (I have not removed this attribute since the warn command is still dependent on it.) Data inserted into the database should remain in the same format as before this change.
This is a refactoring of the mute commands (which are already in use) to escape values in SQL queries to prevent SQLi attacks. To test, your bot must have admin permissions (adding the Admin role in the dev test server will do) to mute/unmute/temporarily mute users. Alt accounts already exist in the dev server which can be used to test this command.
> Escape SQL query values

- commands/utility/warn.js
Closes #87.
Escape values in SQL queries in `warn.js`.
- To test, you must have permission to use the `cc!warn` command. This allows you to warn a user and therefore write a record into the `infractions` and `mod_log` tables.
> Escape values in warn command queries

- commands/mute/tempmute.js
- commands/utility/help.js
Closes #90.
Edited cc!help to include new commands since it was last updated. `cc!help` now sends a MessageEmbed of the commands (sectioned by role access) rather than all the commands and descriptions. This is because we now have too many commands to be able to effectively list them all. Using `cc!help [command]` will still provide the user with the description specific to that command.
Side note: I also updated cc!tempmute to allow SUs to use it (this was an oversight when I initially wrote the command).
> Update help command

- utils/data/db.js
Closes #83
I am also going to work on a script that allows for creating/recreating a single table and adding single columns to existing tables.  Hopefully then it will be easier for @Vic-ST to update the production db. 
Adds `msg_counter` and `user_notes` tables to the db-recreate script.
- Is recreating the database necessary? YES
- Any special requirements to test? Just run `npm run db-recreate` and check that the tables were made.
> Add msg_counter and user_notes tables

- README.md
- app.js
- commands/utility/help.js
- commands/utility/helpcenter.js
- commands/utility/stats.js
Closes #104.
- Add `cc!helpcenter`, which provides links to CC's Help Center and Submit A Request form.
- If `plaintext` is provided as an argument, the links will be sent as plain text rather than an embed. This allows the links to be copied and pasted on mobile.
- Updated README.md and cc!help to include this new command.
- _Minor unrelated change:_ imported `discord.js` directly into the `cc!stats` command rather than having it passed as an argument into `execute()` to be consistent with the other commands.
> Add cc!helpcenter

- app.js
- commands/moderation/ban.js
- commands/moderation/kick.js
- commands/moderation/tempban.js
- commands/mute/mute.js
- commands/mute/tempmute.js
- commands/mute/unmute.js
- commands/utility/warn.js
Closes #112.
- Most of our commands currently only accept a user mention that specifies what user the command should act on. These changes allow for both user mentions and user IDs to be used in all commands (with the exception of `cc!unban`, where only the user ID can be passed).
- Minor unrelated change: fixed a bug in the ban command that threw an error when no arguments were provided.
- Is a re-seeding of the database necessary? **No**
- Any new dependencies to install? **No**
- Any special requirements to test? **You must have permission to use all the commands (Admin role).**
> Enable all commands to take in user ID

- commands/utility/helpcenter.js
Closes #130
Added the following to the cc!helpcenter command when plaintext is specified. This was already done in the embedded version in #121.
**Bug Reporting:** To report a bug, click *Get Unstuck* in the learning environment, then click *Bugs*.
> Add bug reporting to plaintext

- commands/moderation/tempban.js
- commands/mute/tempmute.js
Closes #134
Since a multi-word reason will result in each word being saved as a separate element in the `args` array, I've saved all of them into `reasonArray` and joined them together as a string before saving them in `data.reason`. Multi-word reasons should now work as expected for the `cc!tempmute` and `cc!tempban` commands (which are the ones that use regex for command format validation).
Also made a minor change to `cc!tempmute` so that it replies with the length of time the user was muted for in the channel that the command was used in, and also no longer sends a message in that same channel indicating that the user was unmuted (which is still sent in #audit-logs). This makes it consistent with how `cc!tempban` works.
- Is a re-seeding of the database necessary? **No.**
- Any new …
> Allow multi-word reasons for commands using regex validation

- README.md
- app.js
- commands/moderation/notes.js
- commands/moderation/removenote.js
- commands/utility/clearinfractions.js
- commands/utility/help.js
- commands/utility/removeinfraction.js
- utils/data/tables.js
Closes #128.
- `cc!removenote` sets a note to invalid.
- `cc!notes` now only displays notes which are valid.
- The database recreation function includes a new column in the `user_notes` table named `valid` to differentiate between active and "removed" notes.
- `cc!removenote` was added to README and cc!help.
- Minor unrelated change: added permissions required for several commands in cc!help.
Run the following command to create the new and necessary `valid` column in the `user_notes` table. Additionally, @Vic-ST, remember to do this on the droplet before merging to master.
```
npm run addcolumn table="user_notes" col="valid" type="BOOLEAN DEFAULT true"
```
- Is a re-seeding of the database necessary? **Users must have notes to be able to have them removed.**
- Any new dependencies to …
> Remove notes

- commands/utility/removeinfraction.js
Closes #132 
Changed the `validateInfractionID()` function to prevent the removal of infractions from unspecified users. Now, the infraction will be removed only if it belongs to the specified user. Nearly identical to what is already implemented in `cc!removenote`.
- Is a re-seeding of the database necessary? Need one infraction to test.
- Any special requirements to test? Usual perms to be able to use `cc!removeinfraction`.
> Only allow infractions belonging to the specified user to be removed

- README.md
- commands/moderation/ban.js
- commands/moderation/unban.js
- commands/utility/help.js
Closes #155 
- Allow mods to ban and unban users.
- Remove the four archived Discourse-related commands from cc!help and README.
- Any special requirements to test? Moderator role.
> Allow mods to ban+unban, remove archived from docs

- commands/moderation/filter.js
Closes #158 
Added the ability to treat '0' as an 'o' so that spellings such as 'g0damn' are not missed.
As an extra I went ahead and changed the filter to log everything to swear-jar channel, though this is controlled by a constant variable `autoMod` so it can be reverted quickly.
Can't have SU, Mod, or Admin for the filter to check your messages
> filter update

- commands/moderation/addnote.js
- commands/moderation/ban.js
- commands/moderation/clearmessages.js
- commands/moderation/filter.js
- commands/moderation/kick.js
- commands/moderation/notes.js
- commands/moderation/removenote.js
- commands/moderation/tempban.js
- commands/moderation/unban.js
- commands/mute/mute.js
- commands/mute/tempmute.js
- commands/mute/unmute.js
- commands/utility/clearinfractions.js
- commands/utility/help.js
- commands/utility/helpcenter.js
- commands/utility/infractions.js
- commands/utility/ping.js
- commands/utility/removeinfraction.js
- commands/utility/stats.js
- commands/utility/warn.js
- handlers/messageHandlers.js
Closes #119 
Added a `guildOnly` property to allow opting in and out of DM capability
for various commands.
The only two commands that I put as `guildOnly: false` are `cc!help` and `cc!helpcenter`.
- Any special requirements to test? NO
> Fix bot error when a command is given inside a DM channel

- .github/workflows/action_workflow.yml
`npm ci` will do a fresh install of all node_modules and will not alter the local `package-lock.json` the way `npm install` sometimes will.  It will download and install packages based on what is in the remote `master` branch's `package-lock.json`.
(originally, I changed this directly on Master.  Should have done it on Dev first to begin with.  Will rebase this PR.)
> Update deploy workflow to use `npm ci`

- commands/utility/help.js
- commands/utility/helpcenter.js
- commands/utility/ping.js
- commands/utility/stats.js
- handlers/messageHandlers.js
- handlers/permissionHandlers.js
- helpers/has.js
Closes #122 
Add permissionHandler to DRY perms for commands.
This change helps us avoid duplicate permission handling logic in every
single command file by having a single handler that looks at attributes
of the command for guidance on minimum role needed.
This change requires each command to have the boolean `staffOnly`
attribute.  If `staffOnly` is `true`, then the command should also have
`minRole` attribute with the string name of the minimum role needed to
execute the command.
- Any special requirements to test? 
NO, because this PR only affects the commands that have no minimum role. PRs for Issues 123-125 will require special testing because they will replace the permission handling for all other …
> Add permission handler

- commands/utility/ping.js
After the pong message is sent, comparison is done between the two messages timestamps to find out how long the response took
Closes #184 
When using the cc!ping command the bot will compare the timestamps of your message and its response. It then edits its answer with the time taken in milliseconds.
- Any new dependencies to install? Nada
- Any special requirements to test? Nope
> Added time check

- handlers/messageHandlers.js
Before sending a message to the profanity filter it is checked for a webhook ID, and ignored if it has one.
Closes #183 
The message handler now checks the message for a webhook ID before calling the profanity filter. If there is an ID it ignores it.
- Is a re-seeding of the database necessary? no
- Any new dependencies to install? no
- Any special requirements to test?:
To test it you'll need to have a webhook sent in the development server. You can do this by starting your local bot and then forking the bots repository. The Github bot will then send a webhook on the dev server. 
To test for regular messages you will need to use an account that does not have Super User, Moderator, or Admin roles.
> add webhook check

- commands/moderation/ban.js
- commands/moderation/clearmessages.js
- commands/moderation/kick.js
- commands/moderation/removenote.js
- commands/moderation/tempban.js
- commands/moderation/unban.js
- commands/mute/mute.js
- commands/mute/tempmute.js
- commands/mute/unmute.js
- commands/utility/infractions.js
- commands/utility/removeinfraction.js
- commands/utility/warn.js
Closes #124 
Migrates the last of the commands to use the permission handler.
These are all Mod+ commands.
- Any special requirements to test? YES
- ⚠️ The best way to test this is to take away all your alt account's roles and then give it (one at a time) Code Counselor or Moderator roles.  Then have your alt try to use all the commands here against your main account.
- The Alt should not be able to do this when it has the Code Counselor role (it will receive the message that it does not have the permissions)
- The alt _should_ be able to use these commands as a Moderator, but it can't add notes to a staff member, so it will say that.  That's okay. So long as it doesn't give the permission error about …
> Migrate all Mod+ commands to use Permission Handler

- commands/moderation/addnote.js
- commands/moderation/notes.js
Closes #125 
Remove old permission check inside of the `addnote` and `notes` commands
and update them to the new permission handler.
Remove old SU permission and replace with Code Counselor perms.
- Any special requirements to test? YES
- ⚠️ The best way to test this is to take away all your alt account's roles and then give it (one at a time) Forums Super User or Code Counselor roles.  Then have your alt try to add/view notes on your main account.
- The Alt should not be able to do this when it has the FSU role (it will receive the message that it does not have the permissions)
- The alt _should_ be able to add/view notes as a Code Counselor, but it can't add notes to a staff member, so it will say …
> Update note permissions for Code Counselors

- commands/moderation/verbal.js
- handlers/permissionHandlers.js
Closes #178 
Added the `cc!verbal` command. Functions essentially the same way as `cc!warn` but makes records in `user_notes` rather than `infractions` (also logs to `mod_log`). Stops the execution of the command and sends feedback if an error is encountered while trying to send a DM to the specified user. (Might need to consider refactoring this error handling since it will pick up any errors, not just the specific DM unavailable error; already tried `instanceof` and `.name` to no avail. Error handling for closed DMs should also be implemented in `cc!warn` in the future.)
- Any special requirements to test? Moderator role or higher required. To test error handling for closed DMs, the user being …
> Add cc!verbal command

- commands/moderation/addnote.js
- commands/moderation/filter.js
- commands/mute/mute.js
- commands/mute/tempmute.js
- commands/utility/warn.js
Edited the list of immune roles for the applicable commands:
- `Super Admin` added to all.
- `Super User` changed to `Forums Super User` (the actual role on Discord still needs to be renamed).
- Code Counselors are now immune to the word filter.
- FSUs are now immune to warns, mutes, and tempmutes.
- Any special requirements to test? Minimum role for the most restrictive command is Moderator.
> Update immune roles

- README.md
- commands/utility/help.js
Add documentation of `cc!verbal` (added in #202) to the README and cc!help command.
> Add verbal to README and cc!help

- handlers/messageHandlers.js
Closes #233
Check for the msg.member property in messageHandler so that there is no TypeError in the filter command. Also, refactor check for msg.guild and move web-hook validation to the top.
All prior commands should work. It's likely that this will result in no more TypeErrors due to msg.member being null in the filter command.
Checking for !msg.guild like this is shown in the discord.js docs here: https://discord.js.org/#/docs/discord.js/v12/examples/moderation
- Any special requirements to test? Try various incoming messages (DM, webhook, bot-commands, text)
I have tested basic behaviour: DMs, webhooks, bot-commands and text. Appreciate some further testing to confirm that this will work well.
> validate msg.member in messageHandler function

- package-lock.json
- package.json
No official issue.
Adds nodemon as a dev dependency and script `npm run watch` to start the app with nodemon. Nodemon watches for filechanges and automatically restarts the app when a file has been changed and saved. This makes development easier because you don't have to Ctrl+C and restart the bot every time you make a change.
- Any new dependencies to install? ✔️ 
> Add nodemon to watch for file changes live

- app.js
- commands/utility/help.js
- commands/utility/helpcenter.js
- commands/utility/stats.js
Closes #241 
Updates embeds to be compatible with v13
Adjusts stats command to account for `member.presence` possibly being null now.
Uses `messageCreate` event instead of deprecated `message` event.
- Any new dependencies to install? You might wanna do a fresh `npm install` for testing since some changes were made to the v13 feature branch
> Migrate stats, help and helpcenter commands to v13

- handlers/messageHandlers.js
Closes #265
Changes the property webhookID to webhookId for discord.js v13 port.
You can send webhook msgs to the channel and notice that there was an error prior to this PR fix that should no longer occur with the PR.
> update webhook msg handling for discord.js v13

- app.js
- handlers/errorHandlers.js
Closes #271
Adds global error handling for unhandled promise rejections in order to avoid server crash on these errors. Also sends an some error info in a channel to bot developers.
> handle unhandled promise rejections with node 16

- app.js
- commands/mute/mute.js
- commands/mute/unmute.js
- handlers/channelHandlers.js
- handlers/guildHandlers.js
Closes #273 
Closes #218 
- Update role creation and completely refactor muting
- Update new channel muting
I've refactored how the handling works. The role creation remains the same, and the same process still runs when a new channel is created. However, instead of updated channel overwrites every time the `guildMemberUpdate` event runs (which is every nickname change, role change of a user, etc.), it now runs just once when the role is created and creates permanent permission overrides for the `On Mute` role in all channels.
With the new update to threads, I've denied permissions for muted users to create or send messages in threads as well. They also cannot upload files or use slash commands.
When we upgrade the actual bot on the community server, this will necessitate completely …
> Update mute handling for v13

- app.js
- handlers/channelHandlers.js
- handlers/guildHandlers.js
Closes #280 
`applyMute()` was previously only running if the bot itself created the `On Mute` role. However, with the change to make the bot skip this role creation process if the role already existed in the server this meant message sending permissions were not being denied to the `On Mute` role in each channel. These changes fix that by having `applyMute()` run whether or not the role was created by the bot.
- Any special requirements to test? Need to be able to view Permissions section of channel settings
> Make applyMute run when role already exists

- handlers/errorHandlers.js
Closes #283 
Moves setting of the channel for bot errors to the .env file.
Set the channel in the .env file with the variable BOT_ERROR_CHANNEL_ID. You can add the line below to the .env file:
BOT_ERROR_CHANNEL_ID=ID_FOR_audit-logs
> move bot error channel config to env file

- handlers/messageHandlers.js
Closes #284
Fixes an unhandled promise rejection TypeError bug on message deletion in the discord.js v13 port. Replaces Discord.Util.delayFor with node timer functionality to achieve the same delay as was implemented before.
> fix bug during msg deletion in discord.js v13 port

- commands/moderation/notes.js
- commands/utility/infractions.js
Closes #144
Uses a separate embed field for each record in the notes and infractions commands. This allows much more data than the previous limit which was 1024 chars for all records. Now the limit is a max of 25 records (fields) which each can contain 1024 chars or a total of 6000 chars for the entire embed.
A solution that is using an embed needs to stay within discord.js embed limits: https://discordjs.guide/popular-topics/embeds.html#embed-limits
> use separate fields for notes/infractions records

- commands/moderation/notes.js
- commands/utility/infractions.js
- package-lock.json
- package.json
Closes #126
There was repetitive code in infractions and notes to print how long ago an event occurred. This refactor uses a function from the date-fns library to simplify the code. Also, in case we need additional time related functionality date-fns is one of the better options.
Discovered during refactoring:
There also appears to be a bug in current code related to calculating parts of the time string. For example in the code below how seconds are calculated appears to be incorrect. If minutes is 2.5 this will calculate 3 sec instead of 30 sec:
```js
timeSinceNote[idx] = [
`${Math.floor(minutes)}m ${Math.round(minutes % 60)}s`,
];
````
Using date-fns library solves this issue and simplifies our code.
Npm info: https://www.npmjs.com/package/date-fns
Library docs: https://date-fns.org/
- …
> use date-fns for notes/infractions time-ago

- app.js
- config/db.js
- package-lock.json
- package.json
- utils/data/db.js
Closes #304
Replaces mysql with mysql2 library and incorporates connection pooling. The mysql2 library supports using both callbacks and promises from the same connection pool. The mysql2 syntax is mostly compatible with mysql and previous callback code should therefore work while this allows us to incorporate async/await with the db calls going forward.
The file db.js exports two properties:
```js
module.exports = {
promisePool,
getConnection: () => pool,
};
```
The promisePool object can be used to call the db with promises and async/await. The getConnection function returns a regular callback compatible pool which works with the current code.
We should conduct fairly extensive testing of this PR since it replaces the DB client library and we want to make sure there are no issues with …
> replace mysql with mysql2 which adds promises

- commands/moderation/timeout.js
- config/slashCommandPermissions.js
- package-lock.json
- package.json
- slash-commands/moderation/timeout.js
Closes #235 
* Added timeout command (both non-slash and slash versions).
* The command times out a user using Discord's new timeout functionality, DMs the user, records the event in audit-logs, and records the event in both the infractions and mod_log tables.
* Mods and above cannot be timed out. Timed out users are automatically un-timed out after the specified time has elapsed (we don't need to code this on our end).
* May still need to discuss the following, which was on the linked issue:
> We need to discuss how this may impact how users contact server staff. As we are currently considering moving to a channel-based ModMail-like tool, that would render users in timeout unable to contact staff.
- Is a re-seeding of the database necessary? **No**
- Any new dependencies to install? …
> Create timeout command

- helpers/sendToAuditLogs.js
- slash-commands/moderation/removenote.js
- slash-commands/moderation/timeout.js
- slash-commands/moderation/verbal.js
Closes #316
Adds an optional targetUser property to to audit log helper function. If the targetUser is included, the function will now generate a thumbnail of that user. If it's not included, it will generate a thumbnail of the interaction user (usually the moderator). Implemented this functionality in those slash commands that were already including a thumbnail of the target user for the text based commands.
> add audit log helper target user thumbnail option

- config/slashCommandPermissions.js
- slash-commands/moderation/ban.js
- slash-commands/moderation/unban.js
Closes #296 
Adds ban and unban slash commands. Ban now works for a user that has DMs disabled or is not part of the guild as long as the user-id is entered. The ban command also includes an option for 0 to 7 days of messages to delete when banning a user. This range was chosen because it's what the discord.js API supports.
I added the command permissions to the commandRoles permission handler for consistency even though now with Discord permissions v2 that functionality of setting command permissions does not work.
Since our programmatic permission setting is currently not working you may need to go to Server Settings -> Interactions -> Your Dev Bot and enable the command manually for the Moderator role and above.
- Any new dependencies to …
> Add ban and unban slash commands

- config/slashCommandPermissions.js
- events/interactionCreate.js
- events/ready.js
- slash-commands/moderation/addnote.js
- slash-commands/moderation/clearmessages.js
- slash-commands/moderation/kick.js
- slash-commands/moderation/notes.js
- slash-commands/moderation/removenote.js
- slash-commands/moderation/removetimeout.js
- slash-commands/moderation/timeout.js
- slash-commands/moderation/verbal.js
- slash-commands/utility/ping.js
Closes #321
Removes slash command permission setting by bulk update method as it's no longer supported by Discord in permissions v2. Moves role permission checks into a handler which checks permissions on interactionCreate event. Removes the default permissions false setting for the slash commands. Guild members will be able to launch all slash commands but a reply error message is presented for commands where the user does not have permission (similar to current text commands).
Redeploy the commands with deployCommands.js.
Check Discord Server Settings - Interactions - "Your test bot" to see the current "Discord" permissions for your slash commands. Confirm that your …
> check slash cmd role perms in interaction handler

- slash-commands/utility/helpcenter.js
Removes "Submit a Request" field from the plaintext version of the helpcenter slash command.
> Remove submit a request from plaintext

- slash-commands/moderation/ban.js
- slash-commands/moderation/unban.js
Closes #334 
These 2 commands (ban and unban) still had setDefaultPermission false from when the slash commands had an older implementation of the Discord permission system and the permissions were configured on deployment. With the current permission check at the command level this is not needed anymore. This line had already been removed from all other commands.
> remove setDefaultPermission from ban/unban
